---
driver:
  forward_agent: yes
  name: vagrant
  vm_hostname: false # do not bother trying to change the hostname (sometimes fails)
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero

transport:
  name: winrm

platforms:
- name: windows-2012R2
  driver_config:
    box: win2012r2-datacenter-chef11.16.2
    vm_hostname: fourthcoffee

suites:
- name: default
  run_list:
    - 'recipe[fourthcoffee]'
  attributes:
    fourthcoffee:
      install_method: _classic
